### ISSUE TITLE
Error when gene in signature list not present in expression matrix

### ISSUE THREAD

**Issue by dstueckm** [jcao89757/SCINA#12]
Hi there,

I noticed a potential bug I wanted to bring to your attention. I was able to run the SCINA() function successfully with 3 signatures (~10 genes each), but got the following error when running plotheat.SCINA().

Error in exp[unlist(signatures), order(factor(results$cell_labels, levels = c(names(signatures),  : 
  subscript out of bounds

Once I removed two genes from the signatures that were not present in the expresison matrix, this error disappears and I can successfully produce a heatmap.

**Comment by jcao89757** [comment]
Hi dstueckm,

Thanks a lot for letting me know the issue! 

You are right that this bug can cause unwanted problems. Now I have fixed the bug and you should be able to apply the plot.SCINA function without any additional processes. 

Thanks again for helping us to improve the tool!

Best regards, Ze
