### ISSUE TITLE
Can't install the package using `install_github`

### ISSUE THREAD

**Issue by zhiiiyang** [jcao89757/SCINA#15]
![image](https://user-images.githubusercontent.com/7269113/134952102-0004f153-4a62-4c06-b798-f8deeafaa909.png)

https://github.com/jcao89757/SCINA/blob/a78956355f68bbb7eb5110df5456a585ca5320b8/R/EM_interface.R#L15

**Comment by jcao89757** [comment]
Hi @zhiiiyang,

Thanks a lot for your interest!

The same problem accured to me and it seems like a bug related to devtools. Before I figure out how to solve this problem, would you please install the package from CRAN, as a work around? The package I posted on the CRAN and in the github repo are the same one. 

Thanks for your interest in our tool!

Best regards, Ze
