### ISSUE TITLE
question about 'allow_unknown' parameter

### ISSUE THREAD

**Issue by dahun73** [jcao89757/SCINA#17]
Hello !

I'm trying to annotate using my gene list. However, unknown labels always came out although I used 'allow_unknown = FALSE' option. I tried to make Seurat object again but result was same... my code is  here:

```scina.data <- as.data.frame(inte.combined@assays$RNA[,])

scina.results <- SCINA(scina.data, list_pnas, max_iter = 100, 
                       convergence_n = 10, 
                       convergence_rate = 0.99,
                       sensitivity_cutoff = 0.9,
                       rm_overlap = TRUE,allow_unknown  = FALSE)  

table(scina.results$cell_labels)
```

Immature_neuron             RGC         unknown 
          18498            1972           11107 

Is there any mistake in my code..?

Thank you in advance!!!

Dahun

**Comment by yzyw0702** [comment]
Hi Dahun,
I am one of the author's friend.
I think she will never be able to answer you.
Bad news is, Ze has just passed away last week.
We are in a very painful situation.
If you want to communicate with the related developer, please contact her previous mentor: Wang, Tao.
https://qbrc.swmed.edu/labs/wanglab/aboutpi.php

Best regards,
Wei

**Comment by dahun73** [comment]
Dear Wei,

I can't believe that news.... Ze was so kind when I asked the question
before.... May she rest in peace.
Also, thank you for information, Wei. Don't mind my question. I will try
again. Everyone who use this nice SCINA tool will remember Ze.


Best regards,
Dahun




2021년 10월 28일 (목) 오전 9:29, youngway ***@***.***>님이 작성:

**Comment by yzyw0702** [comment]
Ze is away, but she will live forever in our mind, and so does SCINA.

**Comment by wtwt5237** [comment]
Thank you, @yzyw0702

**Comment by yzyw0702** [comment]
My pleasure.
