### ISSUE TITLE
License for GitHub and CRAN versions

### ISSUE THREAD

**Issue by pamelarussell** [jcao89757/SCINA#20]
Thank you for this useful package!

I noticed that the GitHub version of the project does not carry an open source license, which restricts any ability to modify or distribute the code. The CRAN version carries the GPL-2 license, which also substantially restricts the ability of published works to use SCINA. ([Here](https://tech.popdata.org/the-gpl-license-and-linking-still-unclear-after-30-years/) is a good summary of the issue for CRAN packages with GPL licenses.)

Would you consider adding a more permissive license to the GitHub version (or better yet, both versions) so that the package can be included in distributed projects that may not be able to carry the GPL-2 license for a variety of reasons?

**Comment by wtwt5237** [comment]
@pamelarussell Hello!

Ze passed away some time ago. I am her supervisor and the corresponding author of this work. I grant permission for you to modify or distribute the codes. If you need a more formal statement or would like to discuss further details, you can reach me via email: tao.wang@utsw.edu

I am glad you found our work useful. The best way to keep Ze in our memory is to let her work/codes live on

Thanks!

Tao

**Comment by yunguan-wang** [comment]
This repo is now being maintained in the QBRC group. Please follow the link here: https://github.com/QBRC/SCINA?organization=QBRC&organization=QBRC. We have added a BSL-3 license in that repo that is more permissive.
Thanks!
Yunguan

**Comment by wtwt5237** [comment]
@pamelarussell 

We have added a license to our QBRC collection of repositories, which includes SCINA. You should be able to use SCINA in your companies' work now

https://github.com/QBRC

Thanks!

Tao

**Comment by pamelarussell** [comment]
Thank you everyone!
