### ISSUE TITLE
annotat the aggregated cluster profile

### ISSUE THREAD

**Issue by Liripo** [jcao89757/SCINA#21]
Hello:
I would like to ask if it is possible to annotate the results with the seurat cluster! Like the cluster parameter of singleR.

**Comment by wtwt5237** [comment]
Hi, @Liripo! 

This request seems to be beyond the scope of SCINA itself. 

To integrate SCINA's results with seurat, I image that you can run SCINA to annotate the cell type of each individual cells, and take a majority vote of the cell types of the cells in each seurat cluster, to assign a cell type label for each cluster? Not sure if this is what you asking, but it sounds like a reasonable approach to me

Thanks!

Tao

**Comment by Liripo** [comment]
Hi, @wtwt5237 
Thank you for your help！
Liripo
