### ISSUE TITLE
SCINA error

### ISSUE THREAD

**Issue by cjhong** [jcao89757/SCINA#7]
I constructed gene markers in CSV file format. Make sure that gene symbols are consistent with the exp matrix. When I called SCINA(), I got the following error!

- - -
Error in chol.default(theta[[i]]$sigma1) : 'a' must have dims > 0
In addition: Warning message:
In min(c(diag(x$sigma1), diag(x$sigma2))) :
  no non-missing arguments to min; returning Inf
- - -

**Comment by jcao89757** [comment]
Hi cj,

Thanks for raising up your question! 

Mostly this error indicates that your signature lists so contain many overlapped genes that, after removing overlaps automatically, one or more signature lists may become NULL lists without any genes. Would you like to set the parameter 'rm_overlap=FALSE' and let me know if your question would be solved?

Thanks again for letting me know!

Best regards, Ze

**Comment by cjhong** [comment]
Thank you, the problem is resolved!

**Comment by ankurnaqib** [comment]
Hi. I am still facing the same issue. My data file is too big so I am not sure if that is the issue but here is my code that I am running:-

as.data.frame(data@assays$RNA[,]) -> scina.data
load(system.file('extdata','example_signatures.RData', package = "SCINA"))

signatures

SCINA(
  scina.data,
  signatures, 
  max_iter = 100, 
  convergence_n = 10, 
  convergence_rate = 0.999, 
  sensitivity_cutoff = 0.9, 
  rm_overlap=FALSE, 
  allow_unknown=TRUE,
  log_file = 'Scina.log'
) -> scina.results

and the error I am getting is

Error in chol.default(theta[[i]]$sigma1) : 'a' must have dims > 0
In addition: Warning messages:
1: In min(c(diag(x$sigma1), diag(x$sigma2))) :
  no non-missing arguments to min; returning Inf
2: In min(c(diag(x$sigma1), diag(x$sigma2))) :
  no non-missing arguments to min; returning Inf
3: In min(c(diag(x$sigma1), diag(x$sigma2))) :
  no non-missing arguments to min; returning Inf

Any advise would be really helpful. Thanks.

**Comment by cjhong** [comment]
As jcao89757 suggested, make sure whether your marker genes for a cell type are a subset of the other.

**Comment by simonmfr** [comment]
I keep getting the same error without a large gene overlap. It might have to do with fotmatting of the gene names? If i randomly remove some entries from the gene list, it works for me.

**Comment by Ivy-ops** [comment]
@cjhong May I know how to make sure "whether your marker genes for a cell type are a subset of the other", if my signatures list is very large? Thanks.

**Comment by cjhong** [comment]
1. For each gene signature set, make sure that each gene member exists in
the single-cell assay. Retain only genes that appear in the input
single-cell matrix.

2. Compare each pair of gene signatures, 
For instance, G1 and G2, 
all(length(setdiff(G1,G2))>0,length(setdiff(G2,G1))>0)
The output should be TRUE.

**Comment by Pedramto89** [comment]
Although I put the 'rm_overlap=FALSE', I still get the error. I am sure no overlapping genes are in my signature gene list.

**Comment by longyingda** [comment]
> Although I put the 'rm_overlap=FALSE', I still get the error. I am sure no overlapping genes are in my signature gene list.

https://github.com/jcao89757/SCINA/issues/23

1, you need to check that the name of your maker gene is correct;
2, you need to check if the gene is present in your expression matrix;
