### ISSUE TITLE
Signature vector where no cell markers match cell types causes an error

### ISSUE THREAD

**Issue by moldach** [jcao89757/SCINA#9]
`signatures` contains multiple signature vectors. I noticed if the user has a signature vector where none of the markers match `exp` the `SCINA::SCINA()` function tosses up an error:

```
library(SCINA)
load(system.file('extdata','example_expmat.RData', package = "SCINA"))
load(system.file('extdata','example_signatures.RData', package = "SCINA"))
exp = exp_test$exp_data
```

If there is one marker in a signature list that doesn't match things are fine:

```
signatures <- list(cd14_monocytes = signatures$cd14_monocytes, b_cells = signatures$b_cells, cd56_nk = c("CLIC3", "CST7", "foo"))
results = SCINA(exp, signatures, max_iter = 100, convergence_n = 10, convergence_rate = 0.999, sensitivity_cutoff = 0.9, rm_overlap=TRUE, allow_unknown=TRUE, log_file='SCINA.log')
```

However, if there is a signature vector where all markers fail to match `SCINA::SCINA()` errors out:

```
signatures <- list(cd14_monocytes = signatures$cd14_monocytes, b_cells = signatures$b_cells, cd56_nk = c("foo", "bar"))
results = SCINA(exp, signatures, max_iter = 100, convergence_n = 10, convergence_rate = 0.999, sensitivity_cutoff = 0.9, rm_overlap=TRUE, allow_unknown=TRUE, log_file='SCINA.log')
```

> Error in chol.default(theta[[i]]$sigma1) : 'a' must have dims > 0
In addition: Warning message:
In min(c(diag(x$sigma1), diag(x$sigma2))) :
  no non-missing arguments to min; returning Inf

It seems to me it would be best to remove empty vectors from the `theta` (list) object. I'll take a shot at a **PR**

**Comment by jcao89757** [comment]
Thank you! My original plan was writting a warning message in the log file and let people know that an empty vector caused the error and stopped the algorithm. Your solution works much better than that. 

Thanks again for your constant help!

**Comment by moldach** [comment]
No problem, happy to help 🙂
